/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author faris
 */
public class Warung extends javax.swing.JFrame {

    
    
    public Warung() {
        
        initComponents();               //untuk menginisialisasi komponen yang ada pada form
        
        jumBakso.setEnabled(false);     //untuk menonaktifkan textfield jumlah bakso
        jumEsCampur.setEnabled(false);  
        jumEsDegan.setEnabled(false);
        jumEsJeruk.setEnabled(false);
        jumEsTeh.setEnabled(false);
        jumRawon.setEnabled(false);
        jumSotoAyam.setEnabled(false);
        jumSotoDaging.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sotoAyam = new javax.swing.JCheckBox();
        jumSotoAyam = new javax.swing.JTextField();
        sotoDaging = new javax.swing.JCheckBox();
        jumSotoDaging = new javax.swing.JTextField();
        rawon = new javax.swing.JCheckBox();
        jumRawon = new javax.swing.JTextField();
        jumBakso = new javax.swing.JTextField();
        bakso = new javax.swing.JCheckBox();
        teh = new javax.swing.JCheckBox();
        jumEsTeh = new javax.swing.JTextField();
        jumEsJeruk = new javax.swing.JTextField();
        jeruk = new javax.swing.JCheckBox();
        degan = new javax.swing.JCheckBox();
        jumEsDegan = new javax.swing.JTextField();
        campur = new javax.swing.JCheckBox();
        jumEsCampur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        total = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WARUNG MAKAN KANG SHOLEH");

        sotoAyam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sotoAyam.setForeground(new java.awt.Color(255, 255, 255));
        sotoAyam.setText("Soto Ayam Rp 15.000");
        sotoAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoAyamActionPerformed(evt);
            }
        });

        sotoDaging.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sotoDaging.setForeground(new java.awt.Color(255, 255, 255));
        sotoDaging.setText("Soto Daging Rp 20.000");
        sotoDaging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoDagingActionPerformed(evt);
            }
        });

        rawon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rawon.setForeground(new java.awt.Color(255, 255, 255));
        rawon.setText("Rawon Rp 15.000");
        rawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawonActionPerformed(evt);
            }
        });

        bakso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bakso.setForeground(new java.awt.Color(255, 255, 255));
        bakso.setText("Bakso Rp 10.000");
        bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baksoActionPerformed(evt);
            }
        });

        teh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        teh.setForeground(new java.awt.Color(255, 255, 255));
        teh.setText("Es Teh Rp 3.000");
        teh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehActionPerformed(evt);
            }
        });

        jeruk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jeruk.setForeground(new java.awt.Color(255, 255, 255));
        jeruk.setText("Es Jeruk Rp 4.000");
        jeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jerukActionPerformed(evt);
            }
        });

        degan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        degan.setForeground(new java.awt.Color(255, 255, 255));
        degan.setText("Es Degan Rp 9.000");
        degan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deganActionPerformed(evt);
            }
        });

        campur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        campur.setForeground(new java.awt.Color(255, 255, 255));
        campur.setText("Es Campur Rp 10.000");
        campur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campurActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOTAL");

        bayar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bayar.setText("Bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        print.setText("Cetak Struk");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(sotoAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumSotoAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(sotoDaging, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumSotoDaging, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(rawon, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumRawon, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bakso, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(teh, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(degan, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jumEsDegan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campur, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(print, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jumEsCampur, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(total))))
                            .addComponent(jSeparator1)
                            .addComponent(bayar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sotoAyam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumSotoAyam))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sotoDaging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumSotoDaging, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rawon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumRawon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bakso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumBakso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jeruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(degan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumEsDegan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jumEsCampur, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campur))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    private void campurActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(campur.isSelected()== true){     //jika checkbox campur di klik maka textfield jumlah es campur akan aktif
            jumEsCampur.setEnabled(true);   //menganaktifkan textfield jumlah es campur

        }else{                               //jika checkbox campur tidak di klik maka textfield jumlah es campur akan tidak aktif
            jumEsCampur.setEnabled(false);  //menonaktifkan textfield jumlah es campur
            jumEsCampur.setText("");        //mengosongkan textfield jumlah es campur
        }
    }                                      

    private void deganActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if(degan.isSelected()== true){      //jika checkbox degan di klik maka textfield jumlah es degan akan aktif
            jumEsDegan.setEnabled(true);    //menganaktifkan textfield jumlah es degan
        }else{
            jumEsDegan.setEnabled(false);   //menonaktifkan textfield jumlah es degan
            jumEsDegan.setText("");         //mengosongkan textfield jumlah es degan
        }
    }                                     

    private void jerukActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if(jeruk.isSelected()== true){
            jumEsJeruk.setEnabled(true);
        }else{
            jumEsJeruk.setEnabled(false);
            jumEsJeruk.setText("");
        }
    }                                     

    private void tehActionPerformed(java.awt.event.ActionEvent evt) {                                    
        if(teh.isSelected()== true){
            jumEsTeh.setEnabled(true);
        }else{
            jumEsTeh.setEnabled(false);
            jumEsTeh.setText("");
        }
    }                                   

    private void baksoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if(bakso.isSelected()== true){
            jumBakso.setEnabled(true);
        }else{
            jumBakso.setEnabled(false);
            jumBakso.setText("");
        }
    }                                     

    private void rawonActionPerformed(java.awt.event.ActionEvent evt) {                                      
        if(rawon.isSelected()== true){
            jumRawon.setEnabled(true);
        }else{
            jumRawon.setEnabled(false);
            jumRawon.setText("");
        }
    }                                     

    private void sotoDagingActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        if(sotoDaging.isSelected()== true){
            jumSotoDaging.setEnabled(true);
        }else{
            jumSotoDaging.setEnabled(false);
            jumSotoDaging.setText("");
        }
        
    }                                          

    private void sotoAyamActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        if(sotoAyam.isSelected()== true){
            jumSotoAyam.setEnabled(true);
        }else{
            jumSotoAyam.setEnabled(false);
            jumSotoAyam.setText("");
        }
        
    }                                        

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {                                      

        int soyam,soging,ra,bak,te,jer,deg,camp,tot; //variabel untuk menampung jumlah produk yang di pesan
        
        ArrayList<String> namaProduk = new ArrayList<String>(); //arraylist untuk menampung nama produk yang di pesan
        
        if(sotoAyam.isSelected()){  //jika checkbox soto ayam di klik maka akan menambahkan nama produk soto ayam ke arraylist nama produk
            soyam=Integer.valueOf(jumSotoAyam.getText());   //mengambil nilai dari textfield jumlah soto ayam dan di konversi ke integer
            namaProduk.add("Soto Ayam Rp 15.000");          //menambahkan nama produk soto ayam ke arraylist nama produk
        }else{
            soyam=0;    //jika checkbox soto ayam tidak di klik maka nilai variabel soyam akan di isi 0
        }
        
        if(sotoDaging.isSelected()){        //jika checkbox soto daging di klik maka akan menambahkan nama produk soto daging ke arraylist nama produk
            soging=Integer.valueOf(jumSotoDaging.getText());    //mengambil nilai dari textfield jumlah soto daging dan di konversi ke integer
            namaProduk.add("Soto Daging Rp 20.000");            //menambahkan nama produk soto daging ke arraylist nama produk
        }else{
            soging=0;   //jika checkbox soto daging tidak di klik maka nilai variabel soging akan di isi 0
        }
        
        if(rawon.isSelected()){
            ra=Integer.valueOf(jumRawon.getText());
            namaProduk.add("Rawon Rp 15.000");
        }else{
            ra=0;
        }
        
        if(bakso.isSelected()){
            bak=Integer.valueOf(jumBakso.getText());
            namaProduk.add("Bakso Rp 10.000");
        }else{
            bak=0;
        }
        
        if(teh.isSelected()){
            te=Integer.valueOf(jumEsTeh.getText());
            namaProduk.add("Es Teh Rp 3000");
        }else{
            te=0;
        }
        
        if(jeruk.isSelected()){
            jer=Integer.valueOf(jumEsJeruk.getText());
            namaProduk.add("Es Jeruk Rp 4000");
        }else{
            jer=0;
        }
        
        if(degan.isSelected()){
            deg=Integer.valueOf(jumEsDegan.getText());
            namaProduk.add("Es Degan Rp 9000");
        }else{
            deg=0;
        }
        
        if(campur.isSelected()){
            camp=Integer.valueOf(jumEsCampur.getText());
            namaProduk.add("Es Campur Rp 10.000");
        }else{
            camp=0;
        }
        
      
        
        
        tot=(soyam*15000)+(soging*20000)+(ra*15000)+(bak*10000)+(te*3000)+(jer*4000)+(deg*9000)+(camp*10000);   //menghitung total harga yang harus di bayar
        
         try{
            File myObj = new File("struck.txt");    //berfungsi untuk membuat atau membuka file struck.txt
            
            if(myObj.createNewFile()){      //jika file struck.txt tidak ada maka akan membuat file baru
                System.out.println("File created : "+ myObj.getName()); //menampilkan pesan file berhasil dibuat
            }else{
                System.out.println("File already exists");  //jika file struck.txt sudah ada maka akan menampilkan pesan file sudah ada
            }
            
        }catch(IOException a){  //jika terjadi error maka akan menampilkan pesan error
            a.printStackTrace();    //menampilkan pesan error pada console
        }
        
        
        
        try{
            
            FileWriter fw = new FileWriter("struck.txt");   //berfungsi untuk menulis ke file struck.txt
            BufferedWriter bw = new BufferedWriter(fw);    //berfungsi untuk menulis ke file struck.txt dengan buffer 
            
            bw.write("+-------------------------+\n");  
            bw.write("| WARUNG MAKAN KANG SOLEH |\n");
            bw.write("+-------------------------+\n");

            for (int i = 0; i < namaProduk.size(); i++) {   //perulangan untuk menampilkan nama produk yang di pesan
                bw.write(i+1+". "+namaProduk.get(i)+"\n");  //menulis nama produk yang di pesan ke file struck.txt
            }
            bw.write("\nTotal "+ tot);   //menulis total harga yang harus di bayar ke file struck.txt
            bw.close(); //menutup file struck.txt
        }catch(IOException a){
            a.printStackTrace();
        }
        
      
        total.setText( String.valueOf(tot) );   //menampilkan total harga yang harus di bayar pada textfield total
        
    }                                     

    private void printActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox bakso;
    private javax.swing.JButton bayar;
    private javax.swing.JCheckBox campur;
    private javax.swing.JCheckBox degan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jeruk;
    private javax.swing.JTextField jumBakso;
    private javax.swing.JTextField jumEsCampur;
    private javax.swing.JTextField jumEsDegan;
    private javax.swing.JTextField jumEsJeruk;
    private javax.swing.JTextField jumEsTeh;
    private javax.swing.JTextField jumRawon;
    private javax.swing.JTextField jumSotoAyam;
    private javax.swing.JTextField jumSotoDaging;
    private javax.swing.JButton print;
    private javax.swing.JCheckBox rawon;
    private javax.swing.JCheckBox sotoAyam;
    private javax.swing.JCheckBox sotoDaging;
    private javax.swing.JCheckBox teh;
    private javax.swing.JLabel total;
    // End of variables declaration                   
}
